### PR TITLE
Support EIP712 for Message Signing

### LINKED ISSUE #3: Support EIP712 for Message Signing
As recently merged to the final stage of the [EIP712](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md) supports signing typed data to clearly inform of the User the contents of the message being signed

A detailed walkthrough of the specification and implementation by Metamask can be found on this article written by Dan Finlay: https://medium.com/metamask/scaling-web3-with-signtypeddata-91d6efc8b290

**Acceptance Criteria**
* Enforce message to follow the type named structure
* Describe on the PR which param were made required or optional
* Provide explicit errors for developer debugging

### PR DESCRIPTION
**Pull request by hbeckeri**
resolves #3

### CODE REVIEW

**Comment by pedrouid** [comment]
Nice one @hbeckeri!

Review:
* The method `encrypt` is a generic method for all payloads to be sent to the bridge. Include an encryptMessage method that handles the validation of typed data and consequently calls `encrypt`.
* On the typedDataSchema also enumerate that parameter types have to match a solidity type
* Describe on this PR examples of a typed data message with only required parameters and another including also optional parameters

**Comment by hbeckeri** [comment]
@pedrouid I am ready for further review

**Comment by mkosowsk** [comment]
Hi @pedrouid do you have a chance to review latest changes from @hbeckeri ? Thanks! :)

**Comment by hbeckeri** [comment]
@mkosowsk Looks like we are all clear for merge

**Pull request merged**
